version: '3.9'

services:
  database:
    image: postgres:alpine
    hostname: localhost
    container_name: bookie-main-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always

volumes:
  postgres:
