version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: bookie-main-postgres
    hostname: localhost
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always

  app:
    image: winonaivana/bookie-backend
    container_name: bookie-backend-app
    build: .
    ports:
      - 80:4000
      - 443:4000
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - database
    restart: always

volumes:
  postgres:
